### ISSUE TITLE
Example Code

### ISSUE THREAD

**Issue by oscartbeaumont** [Erk-/spotrust#1]
Is There Any Example Code For This Because I Am Looking To Use It For A Project And Don't Know How To Use It.

**Comment by Erk-** [comment]
I will make some this weekend.

**Comment by Erk-** [comment]
I have now added a simple example [here](https://github.com/Erk-/spotrust/blob/master/examples/basic_example/src/main.rs) to be fair the wrapper is not too nice to use now and it is still missing a lot of end points, if you need any specific feel free to ask and I will add them.

**Comment by oscartbeaumont** [comment]
Thanks for your help.

**Comment by oscartbeaumont** [comment]
Can you get a list of the songs in a playlist using the `track_get_tracks` method? If not how would I get the songs that are in a playlist from its URI.

**Comment by Erk-** [comment]
I have added an function to get the tracks of a playlist and an example on how to use it, in [8142420](https://github.com/Erk-/spotrust/commit/8142420154e2adbb1fcdf71342227601172feff0). I also bumped the version to 0.0.5 so you may need to update your Cargo.toml and run cargo update I am not deserialising the userobject anymore as Spotify does not follow thier own api with the type. Please say if you have any questions or if you think there is missing anything.

**Comment by oscartbeaumont** [comment]
I have [linked to some code](https://github.com/oscartbeaumont/TEMP-Spotify-RUST) (An Example Program and Modified Version of This Repo) which is my attempt at trying to implement authorization_code authenticate (Which Allows The API To Access Certain Bits Of Users Data). I would like to be able to add and remove a song from a playlist on the user's account. It works for authenticating getting the `spotify_token` returned but I do not know how I can make that accessible from other parts of the program.
As A Note The Code Is Messy, Hasn't Been Cleaned Up And I Am New To RUST So It May Be Messy. If the code unusable just ignore and add that feature how you would.

Thanks for your help and your time.

**Comment by Erk-** [comment]
You could try and use [lazy_static](https://docs.rs/lazy_static/1.0.0/lazy_static/) to make it a "global" variable. When I get some time I will rewrite the api to use traits instead of the a bit strange function I use now,

**Comment by Erk-** [comment]
@oscartbeaumont Just a heads up, at easter I think I will make a lot of braking changes to the crate. As I will change the way a lot of functions work from being functions to using traits, for example if you need to get a auth token you will write something like `let authToken = AuthToken::new(id, secret);` and at the same time change a lot of the track functions to impl and traits.
